apiVersion: apps/v1
kind: Deployment
metadata:
  name: maker
  namespace: tea
  labels:
    app: maker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maker
  template:
    metadata:
      labels:
        app: maker
    spec:
      containers:
        - name: maker
          image: 192.168.66.10:5000/maker:v1.0
          ports:
            - containerPort: 8082
          env:
          - name: TZ
            value: "Asia/Shanghai"
          - name: JAVA_TOOL_OPTIONS
            value: "-javaagent:/opt/skywalking/agent/skywalking-agent.jar -Dskywalking.agent.service_name=maker -Dskywalking.collector.backend_service=192.168.66.100:11800"
          volumeMounts:
          - name: skywalking-agent
            mountPath: /opt/skywalking/agent
      volumes:
      - name: skywalking-agent
        hostPath:
          path: /opt/skywalking/agent
---
apiVersion: v1
kind: Service
metadata:
  name: maker
  namespace: tea
spec:
  type: ClusterIP
  selector:
    app: maker
  ports:
    - port: 8082
      targetPort: 8082