server:
  port: 8080

spring:
  application:
    name: binarytea

  thymeleaf:
    cache: false

  web:
    resource:
      cache:
        cachecontrol:
          max-age: 60
          cache-public: true
  # Consul, Sentinel
  cloud:
    consul:
      host: 192.168.66.100
      port: 8500
      discovery:
        healthCheckPath: ${management.server.servlet.context-path}/actuator/health
        serviceName: ${spring.application.name}
    sentinel:
      transport:
        dashboard: 192.168.66.100:8090
        port: 8719
  # DB
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.66.100:3306/binarytea
      username: root
      password: root

management:
  endpoint:
    health:
      show-details: always
  web:
    exposure:
      include: health,info,shop,metrics,refresh,env

# -javaagent:D:\PROJECTS\skywalking-agent\skywalking-agent.jar -Dskywalking.agent.service_name=binarytea -Dskywalking.collector.backend_service=192.168.66.100:11800
